#include "level_data.h"

level_data LEVELS[NUM_LEVELS] = {
    [0] = {
        .title = "$35SPECIAL DELIVERY",
        .map = {
            "                   ",
            "    t    x         ",
            "               x   ",
            "    x      x       ",
            "                   ",
            "                   ",
            "SrrrrrrrrrrrrrrrrrF",
            "                   ",
            "        x          ",
            "                t  ",
            "                   ",
            "    x              ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 2 },
        },
        .bonus = 100
    },
    [1] = {
        .title = "$26CURVE IN THE ROAD",
        .map = {
            "                   ",
            "       x       t   ",
            "                   ",
            "     t     x       ",
            "               x   ",
            "        rrrrrrrrrrF",
            "     l  r          ",
            "Srrrrrrrr          ",
            "         l   x     ",
            "     x             ",
            "              t    ",
            "           x       ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 4 },
        },
        .bonus = 150
    },
    [2] = {
        .title = "$42FAT L",
        .map = {
            "        S          ",
            "       xr      t   ",
            "        r          ",
            "     t  r  x       ",
            "        r      x   ",
            "        r          ",
            "        r          ",
            "        r          ",
            "        r    x     ",
            "     x  r          ",
            "        rrrrrrrrrrF",
            "           x       ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 2 },
            { ENTITY_SHIP_L1, 2 },
        },
        .bonus = 200
    },
    [3] = {
        .title = "$55U TURN",
        .map = {
            "  S       F        ",
            "  r    x  r    t   ",
            "  r       r        ",
            "  r  t    rx       ",
            "  r       r    x   ",
            "  r       r        ",
            "  r       r        ",
            "  r       r        ",
            "  r       r  x     ",
            "  r  x    r        ",
            "  rrrrrrrrr        ",
            "           x       ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 2 },
            { ENTITY_SHIP_L1, 4 },
        },
        .bonus = 250
    },
    [4] = {
        .title = "$36EASY MONEY",
        .map = {
            "           x  x    ",
            "  x  t             ",
            "    x    t   x l   ",
            "                   ",
            "xxxxxxxxxxxxxxxxxxx",
            "     t   xx  x     ",
            "SrrrrrrrrrrrrrrrrrF",
            "       x      t    ",
            "xxxxxxxxxxxxxxxxxxx",
            "     l             ",
            "    xxx   x        ",
            "       x       x   ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 10 },
        },
        .bonus = 300
    },
    [5] = {
        .title = "$50LAKESIDE DRIVE",
        .map = {
            "           F       ",
            "     t     r       ",
            "           r    t  ",
            "     x rrrrr       ",
            "  t    r           ",
            "       rrrrrrrr    ",
            "         lll  r    ",
            "     t   lll  r    ",
            "         lll  r    ",
            "Srrrrrrrrrrrrrr    ",
            "                   ",
            "    t     x     t  ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L1, 4 },
            { ENTITY_SHIP_L2, 1 },
        },
        .bonus = 350
    },
    [6] = {
        .title = "$42WETLANDS",
        .map = {
            "hhh hxhhhhh hhhhxhh",
            "hhhhhhhhhhhhhhhhhhh",
            "Srrrrrhh hhhhh hxhh",
            "hhhhhrhhhhhhhhhhhhh",
            "hhhhhrhhhhh hhhhhhh",
            "h hxhrhhhhrrrrrrrrF",
            "hhhhhrhhxhrhhhxhhhh",
            "hhhhhrrrrrrhhhhhxhh",
            "hh hhhhhhhhhhh hhhh",
            "hhhhhhxhhhhhxhhhxhh",
            "hhh hhhhh hhhhhhhhh",
            "hhhhhhxhhhhhhhh hhh",
            "hhhhhhhhhhhhhhhhhhh",
        },
        .ships = {
            { ENTITY_TRANSPORT_L0, 1 },
            { ENTITY_SHIP_L2, 3 },
        },
        .bonus = 450
    },
    [7] = {
        .title = "$06STAIR STEPPER",
        .map = {
            "   x               ",
            "        x   x      ",
            "Srrrrr         t   ",
            "     r    t  x     ",
            "     r             ",
            "  x  rrrrrr   x    ",
            "          r        ",
            "          r        ",
            "  x  x    rrrrr    ",
            "          t   r    ",
            "    x         r    ",
            "    t   x     rrrrF",
            "                   ",
        },
        .ships = {
            { ENTITY_TRANSPORT_L0, 2 },
            { ENTITY_SHIP_L2, 3 },
        },
        .bonus = 600
    },
    [8] = {
        .title = "$50LOOP-DE-LOOP",
        .map = {
            "         x   l     ",
            "  x   l        x   ",
            "     rrrrrrrrrr  x ",
            "  x  r        r    ",
            "  x  r    F   r    ",
            "  x  rrrrrr   r x  ",
            "      x  x    r    ",
            "Srrrrrrrrrrrrrr  l ",
            "   t          x    ",
            "     x    x t      ",
            "     x t  t     x  ",
            "  t          x     ",
            "                   ",
        },
        .ships = {
            { ENTITY_TRANSPORT_L0, 2 },
            { ENTITY_TRANSPORT_L1, 2 },
            { ENTITY_SHIP_L2, 3 },
        },
        .bonus = 750
    },
    [9] = {
        .title = "$36I'M GOING TO\nBE A WHILE...",
        .map = {
            "xxxxxtxxxxxxxxxxxxx",
            "xxtxxxxxxxxxxtxxxxx",
            "    t m       t    ",
            "Srrrrrrrrrrrrrrrrrr",
            "   m  x  tx m     r",
            "rrrrrrrrrrrrrrrrrrr",
            "r t   x   x m  l   ",
            "rrrrrrrrrrrrrrrrrrr",
            "  t   x x x   t   r",
            "rrrrrrrrrrrrrrrrrrr",
            "r  m    x l   x    ",
            "rrrrrrrrrrrrrrrrrrF",
            "     m      m      ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 4 },
        },
        .bonus = 1000
    },
    [11] = {
        .title = "$07MOUNTAIN PASS",
        .map = {
            "              x    ",
            "  t x   x     x    ",
            "               t   ",
            "Srrrrrrrrrm        ",
            "        mrm   x    ",
            " x   l  mrm     x  ",
            "        mrm  x     ",
            "     x  mrm        ",
            "        mrm        ",
            "  x     mrrrrrrrrrF",
            "     x         x   ",
            "   t       x       ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 4 },
        },
        .bonus = 1100
    },
    [12] = {
        .title = "$12SEE YOU ON\nTHE OTHER SIDE",
        .map = {
            "         S   x     ",
            "        mrm     x  ",
            " t x     r         ",
            "        mrm  x     ",
            "   x    mrm        ",
            "        mrm        ",
            "    x   mrm     x  ",
            "  x     mrm        ",
            "        mrm        ",
            "        mrm  x     ",
            " t  x    r         ",
            "        mrm    x   ",
            "         F         ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 4 },
        },
        .bonus = 1250
    },
    [13] = {
        .title = "$39SLUDGY MESS",
        .map = {
            "ddddddddddddSdddddd",
            "ddddddd ddddrdddddd",
            "ddddxdddddddrdd xdd",
            "dd ddddxdd drdddddd",
            "dddxddddddddrddd dd",
            "dd dddrrrrddrdddxdd",
            "ddddddrddrrrrdddxdd",
            "dd dd rddd dddddddd",
            "ddddddrdddxdddddddd",
            "dd dddrrrrddddxdxdd",
            "ddxddddddrdddd dddd",
            "ddd dxd drdddddxddd",
            "dddddddddFdddddd dd",
        },
        .ships = {
            { ENTITY_SHIP_L0, 4 },
        },
        .bonus = 1350
    },
    [14] = {
        .title = "$36MONEY PIT",
        .map = {
            "hhhhhhhhhhhhhhhhhhh",
            "hhhhhrrrrrrrrrrrrrr",
            "hhhhhrhhhhhhhhhhhhh",
            "hhhhhrrrrrrrhhhhhhh",
            "hhhhhxxxxxxrhhhhhhh",
            "hhhhhxxxxxxrhhhhhhh",
            "hhhhhxxxxxxrhhhhhhh",
            "hhhhhxxxxxxrhhhhhhh",
            "hhhhhxxxxxxrhhhhhhh",
            "Srrrrrrrrrrrhhhhhhh",
            "hhhhhhhhhhhhhhhhhhh",
            "hhhhhhhhhhhhhhhhhhh",
            "hhhhhhhhhhhhhhhhhhh",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [15] = {
        .title = "$13TAR PIT",
        .map = {
            "xxxxxxxxxxxxxxxxxx ",
            "xxxxxxxxxxxxxxxxxx ",
            "Srrrrrrrrrrrrrrr   ",
            "     ddddddddddr   ",
            "   x ddddddddddr   ",
            " t   ddddddddddr   ",
            "     rrrrrrrrrrr   ",
            " t x r xxxxxxxxxxx ",
            "     r xxxtxxxxtxx ",
            "     r xxxxxxtxxxx ",
            " x   r xxxxtxxxxxx ",
            "     r xxxxxxxxxxx ",
            "     F xxxxxxxxxxx ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [16] = {
        .title = "$36I'M GOING TO\nBE A WHILE...\n$27(REDUX)",
        .map = {
            "       x     t x   ",
            "Srrrrrrrrrrrrrrrrrr",
            "   t    x d  t x  r",
            "rrrrrrrrrrrrrrrrrrr",
            "r  d   x d  x    t ",
            "rrrrrrrrrrrrrrrrrrr",
            "   d t  x  l d x  r",
            "rrrrrrrrrrrrrrrrrrr",
            "r   d x   t d  x   ",
            "rrrrrrrrrrrrrrrrrrr",
            "  t  d  x   d x   r",
            "Frrrrrrrrrrrrrrrrrr",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [17] = {
        .title = "$06STAIR-ER\nSTEPPER-ER",
        .map = {
            "    x  x    rrrrrrF",
            "          mrr      ",
            "  l   x   rr  t    ",
            "  x      rr     x  ",
            "    x  mrrl   x    ",
            "  x    rr       t  ",
            "      rrm  x  x    ",
            "  x  rr            ",
            "  t rr  l x x   x  ",
            "   rr       x  t   ",
            "  rr  x   t        ",
            "Srr  m      x  x   ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [18] = {
        .title = "$36EASY-ER MONEY-ER",
        .map = {
            "           x  x    ",
            "  x  t             ",
            "    x    t   x l   ",
            "                   ",
            "xxxxxxxxxxxxxxxxxxx",
            "     t   xx  x     ",
            "SrrrrrrrrrrrrrrrrrF",
            "       x      t    ",
            "xxxxxxxxxxxxxxxxxxx",
            "     l             ",
            "    xxx   x        ",
            "       x       x   ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [19] = {
        .title = "$42S\n(LIKE THE COOL ONE\nEVERYONE DRAWS)",
        .map = {
            "         x     x   ",
            "  rrrrrrrrrrrrrrrrS",
            "  rhhhhhhhhhhhhh   ",
            " xrhhhHHHHHHhhhh   ",
            "  rhhhHHHHHHhhhh  x",
            " xrhhhhhhhhhhhhh   ",
            "  rrrrrrrrrrrrrrr  ",
            "  hhhhhhhhhhhhhhr  ",
            "  hhhhHHHHHhhhhhr x",
            "  hhhhHHHHHhhhhhr  ",
            "  hhhhhhhhhhhhhhr  ",
            "Frrrrrrrrrrrrrrrr  ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [20] = {
        .title = "$44ACTUALLY THOSE\nDON'T HAVE TO BE\nON THE MAP EDGES\n",
        .map = {
            "       t           ",
            "  x           x    ",
            "       x           ",
            "  x        x   x   ",
            "                   ",
            "     SrrrrrrrF     ",
            "               t   ",
            "   x               ",
            "      x    x       ",
            "  t           t    ",
            "                   ",
            "    x              ",
            "     x        x    ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [21] = {
        .title = "$44FOR EXAMPLE",
        .map = {
            "   t x             ",
            "          x   x    ",
            " x  m t       m    ",
            "          x        ",
            " m  t   SrF     x  ",
            "   x          m    ",
            "     m    x        ",
            " m          x x  t ",
            "       m           ",
            "  x       x     x  ",
            "     m       m     ",
            "  x     x        t ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [22] = {
        .title = "$22OK I'LL STOP\nHERE'S A LONG ONE",
        .map = {
            " S  x         x    ",
            " r     rrrrr     x ",
            " r   t r   r   t   ",
            " r x   r   r       ",
            " r     r   r       ",
            " r     r t r t x   ",
            " r     r   r       ",
            " r  t  r   r     x ",
            "tr x   r   r x     ",
            " r     r   r    t  ",
            " r  x  r t r       ",
            " rrrrrrr   rrrrrrrF",
            "   t           t   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [23] = {
        .title = "$44JUST KIDDING",
        .map = {
            "        HHH   x    ",
            "  t  x  HSH        ",
            "     x  HrH   x    ",
            "     x  HFH   x    ",
            "     x  HHH   x    ",
            "     x             ",
            "      x     x      ",
            "               t   ",
            "      l  m         ",
            "                   ",
            "    t        l     ",
            "                   ",
            "       x    x      ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [24] = {
        .title = "$61SINUSOIDAL",
        .map = {
            "                   ",
            "                   ",
            "                   ",
            "       rrrrr       ",
            "      rr   rr      ",
            "     rr     rr     ",
            "    rr       rr    ",
            "   rr         rr   ",
            "  rr           rr  ",
            "Srr             rrF",
            "                   ",
            "                   ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [25] = {
        .title = "$07LONELY MOUNTAIN",
        .map = {
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [26] = {
        .title = "$07(NOT SO)\nLONELY MOUNTAIN(S)",
        .map = {
            "     t   S      t  ",
            "  mmmmmmmrmmmmmmm  ",
            "  mmmmm xrx mmmmm t",
            "t mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm  ",
            "  mmmmm xrx mmmmm t",
            "  mmmmmmmrmmmmmmm  ",
            "  t      F         ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [27] = {
        .title = "$51AMBUSH",
        .map = {
            "   h     h       F ",
            "      h    h  h  r ",
            "   h             r ",
            "SrrrrrrrrrrrrrrHHrl",
            "              rHHr ",
            "    x h  l    rHHr ",
            " h         h  rHHr ",
            "      x       rHHr ",
            "   h    h     rHHrl",
            " t    l    h  rHHr ",
            "    h         rHHr ",
            "  h     h  l  rHHr ",
            "              rrrr ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [28] = {
        .title = "$36EASY-EST MONEY-EST",
        .map = {
            "           x  x    ",
            "  x  t             ",
            "    x    t   x l   ",
            "                   ",
            "xxxxxxxxxxxxxxxxxxx",
            "     t   xx  x     ",
            "SrrrrrrrrrrrrrrrrrF",
            "       x      t    ",
            "xxxxxxxxxxxxxxxxxxx",
            "     l             ",
            "    xxx   x        ",
            "       x       x   ",
            "                   ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
    [29] = {
        .title = "$56DEATH SPIRAL",
        .map = {
            "  S    h  h    h   ",
            "  r rrrrrrrrrrrrr h",
            "d r r HH HH HHH r h",
            "  r r rrrrrrrrr r  ",
            "  r r rHHHH   r rh ",
            "l r r rHHHHF  r r  ",
            "  r r rrrrrr  r r h",
            "d r r h    h  r r  ",
            "d r rrrrrrrrrrr r d",
            "  r HHH HHHH HH rh ",
            "l rrrrrrrrrrrrrrr  ",
            "     h  h   h   l d",
            "d  l     h   l   h ",
        },
        .ships = {
            { ENTITY_SHIP_L0, 20 },
        },
        .bonus = 1500
    },
};
